# HTTP 自动跳转 HTTPS
server {
    listen 80;
    server_name ai2god.club www.ai2god.club;
    return 301 https://$host$request_uri;
}



server {
    listen 443 ssl;
    server_name ai2god.club;

    # SSL 证书路径（容器内路径）
    ssl_certificate     ./ssl/ai2god.club_bundle.crt;
    ssl_certificate_key ./ssl/ai2god.club.key;

    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        # root /usr/share/nginx/html;
        # index index.html;
        # try_files $uri $uri/ =404;
        # proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://10.3.0.15:8000;
    }
}


server {
    listen 443 ssl;
    server_name www.ai2god.club;

    # SSL 证书路径（容器内路径）
    ssl_certificate     ./ssl/www.ai2god.club_bundle.crt;
    ssl_certificate_key ./ssl/www.ai2god.club.key;

    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        # root /usr/share/nginx/html;
        # index index.html;
        # try_files $uri $uri/ =404;
        proxy_pass http://10.3.0.15:8000;
    }
}
